### ISSUE TITLE
Error while trying the template

### ISSUE THREAD

**Issue by psanders** [estuary/flow-template#6]
I got stuck while trying the [flow-template](https://github.com/estuary/flow-template/).

After running the `flowctl test --source word-counts.flow.yaml` command I get the following error:

```bash
2022-05-18 16:43:08.227885 I | pkg/flags: recognized and used environment variable ETCD_LOG_LEVEL=error
2022-05-18 16:43:08.228071 I | pkg/flags: recognized and used environment variable ETCD_LOGGER=zap
word-counts.flow.yaml error at /collections/acmeCo~1word-counts/derivation :
derivation uses TypeScript lambdas but defines no TypeScript module
FATA[0000] fatal error                                   err="1 build errors"
```

The error seems to be related to https://github.com/estuary/flow/pull/460 and https://github.com/estuary/flow/pull/473

I tried adding the `derivation.typescript.module=word-counts.flow.ts` and found a TS error. 

![error_screenshot](https://user-images.githubusercontent.com/539774/169104947-7952583b-83a1-4603-aaa9-8db530e7e44c.png)

I will dig a bit more, but I wanted to bring this to your attention.

**Comment by mdibaiee** [comment]
@psanders thank you for filing the issue! You are right, we have updated the way TypeScript modules are generated, but also the way they are referred to in catalog specifications. I will bring this to attention in our team.

**Comment by psFried** [comment]
@psanders Thanks again for bringing this to our attention. This is fixed now, so you should be able to try it out. One thing to note is that we're currently hard at work on a SAAS offering, and a new and improved CLI to go with it. So the rough edges in this workflow (needing to run `temp-data-plane` and exporting env vars) should get smoothed out soon.
